# Generated by Django 5.1.3 on 2024-11-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('retirement', models.IntegerField()),
                ('other_benefits', models.IntegerField()),
                ('total_benefits', models.IntegerField()),
                ('total_compensation', models.IntegerField()),
            ],
        ),
    ]
