# Generated by Django 5.1.3 on 2024-11-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='other_benefits',
            field=models.DecimalField(decimal_places=True, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employe',
            name='retirement',
            field=models.DecimalField(decimal_places=True, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employe',
            name='salary',
            field=models.DecimalField(decimal_places=True, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employe',
            name='total_benefits',
            field=models.DecimalField(decimal_places=True, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employe',
            name='total_compensation',
            field=models.DecimalField(decimal_places=True, max_digits=10),
        ),
    ]
