# Generated by Django 5.1.3 on 2024-11-28 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0003_email_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_tracking',
            name='unique_id',
            field=models.CharField(default='9fd91449', editable=False, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Sent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sent', models.IntegerField()),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Email.email')),
            ],
        ),
    ]
