# Generated by Django 5.1.3 on 2024-11-28 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0004_alter_email_tracking_unique_id_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_tracking',
            name='unique_id',
            field=models.CharField(default='48bdb834', editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sent',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sents', to='Email.email'),
        ),
    ]
