# Generated by Django 5.1.3 on 2024-11-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0006_alter_email_tracking_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_tracking',
            name='unique_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
